import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const toAbsolute = (p: string) => path.resolve(__dirname, p);

// Safe JSON serializer to prevent XSS
export function serializeForScript(data: any): string {
  return JSON.stringify(data)
    .replace(/</g, "\\u003c")
    .replace(/>/g, "\\u003e")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

export function getTemplateWithCriticalCss(templatePath: string): string {
  if (!fs.existsSync(templatePath)) {
    throw new Error(`Template not found at ${templatePath}`);
  }
  
  const template = fs.readFileSync(templatePath, "utf-8");
  let processedTemplate = template;
  
  // Find the CSS file link generated by Vite
  const cssLinkMatch = template.match(/<link rel="stylesheet"[^>]*?href="([^"]+\.css)"[^>]*?>/);
  
  if (cssLinkMatch) {
    const cssHref = cssLinkMatch[1];
    // Convert /assets/style.css -> dist/assets/style.css
    const relativeCssPath = cssHref.startsWith("/") ? cssHref.substring(1) : cssHref;
    const cssPath = toAbsolute(`dist/${relativeCssPath}`);
    
    if (fs.existsSync(cssPath)) {
      console.log(`Inlining CSS from ${cssPath}`);
      const cssContent = fs.readFileSync(cssPath, "utf-8");
      processedTemplate = template.replace(
        cssLinkMatch[0], 
        `<style>${cssContent}</style>`
      );
    } else {
      console.warn(`Warning: CSS file not found at ${cssPath}`);
    }
  }
  
  return processedTemplate;
}

export function writeHtmlForLocale(
  filePath: string, 
  htmlContent: string, 
  locale: string,
  metaDescriptions: Record<string, string>
) {
  let finalHtml = htmlContent;

  // Localize Meta Description
  // Note: This assumes the template starts with the ES description.
  // Ideally, use a placeholder in HTML, but replacement works for now.
  if (locale !== "es" && metaDescriptions[locale] && metaDescriptions["es"]) {
     finalHtml = finalHtml.replace(
      metaDescriptions["es"], 
      metaDescriptions[locale]
    );
  }

  // Ensure directory exists
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(filePath, finalHtml);
  console.log(`✓ Generated ${filePath}`);
}
